### ISSUE TITLE
OGRWriter always returns non-zero

### ISSUE THREAD

**Issue by balazsdukai** [geoflow3d/gfp-gdal#13]
When writing to postgres, the writer always returns at least the error message `loading of _gnm_meta failed`, and exits with non-zero status. 
Even so, the data is written correctly to postgres.
The writer should return 0 on true success.

#10 might solve it :man_shrugging: 

Or keeping track of the tiles and using an alternative connection string for the very first tile that creates a table, while the rest of the tiles don't need to create a table. Check NLExtract for details.

**Comment by balazsdukai** [comment]
Solved with new writer

**Comment by Ylannl** [comment]
I just realized the new writer still gives errors when using `active_schema`. Output is written though.
